# Generated by Django 5.2.8 on 2025-11-19 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('division', '部'), ('section', '課'), ('group', '係'), ('team', '班')], max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='proposals.department')),
            ],
            options={
                'ordering': ['level', 'name'],
                'unique_together': {('name', 'level')},
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management_no', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('proposer_name', models.CharField(max_length=128)),
                ('proposer_email', models.EmailField(blank=True, max_length=254)),
                ('team_name', models.CharField(blank=True, max_length=128)),
                ('problem', models.TextField()),
                ('idea', models.TextField()),
                ('expected_effect', models.TextField(blank=True)),
                ('result_detail', models.TextField(blank=True)),
                ('contribution_business', models.CharField(blank=True, max_length=255)),
                ('reduction_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('effect_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('before_image_url', models.CharField(blank=True, max_length=255)),
                ('after_image_url', models.CharField(blank=True, max_length=255)),
                ('supervisor_status', models.CharField(choices=[('pending', '未確認'), ('approved', '承認'), ('rejected', '差戻し')], default='pending', max_length=20)),
                ('supervisor_comment', models.TextField(blank=True)),
                ('supervisor_checked_at', models.DateTimeField(blank=True, null=True)),
                ('chief_status', models.CharField(choices=[('pending', '未確認'), ('approved', '承認'), ('rejected', '差戻し')], default='pending', max_length=20)),
                ('chief_comment', models.TextField(blank=True)),
                ('chief_checked_at', models.DateTimeField(blank=True, null=True)),
                ('manager_status', models.CharField(choices=[('pending', '未確認'), ('approved', '承認'), ('rejected', '差戻し')], default='pending', max_length=20)),
                ('manager_comment', models.TextField(blank=True)),
                ('manager_checked_at', models.DateTimeField(blank=True, null=True)),
                ('manager_mindset_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('manager_idea_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('manager_hint_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('committee_status', models.CharField(choices=[('pending', '未確認'), ('approved', '承認'), ('rejected', '差戻し')], default='pending', max_length=20)),
                ('committee_comment', models.TextField(blank=True)),
                ('committee_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='proposals.department')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
