# Generated by Django 5.2.8 on 2025-11-19 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(choices=[('staff', '従業員'), ('supervisor', '監督者'), ('chief', '係長'), ('manager', '部門長'), ('committee', '改善委員')], default='staff', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_on', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='proposals.department')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['department__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ImprovementProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management_no', models.CharField(max_length=64, unique=True, verbose_name='管理No')),
                ('submitted_at', models.DateTimeField(verbose_name='提出日時')),
                ('affiliation', models.CharField(blank=True, max_length=128, verbose_name='所属担当')),
                ('deployment_item', models.CharField(blank=True, max_length=255, verbose_name='展開項目')),
                ('proposer_name', models.CharField(max_length=128, verbose_name='提案者')),
                ('problem_summary', models.TextField(verbose_name='問題点')),
                ('improvement_plan', models.TextField(verbose_name='改善案')),
                ('improvement_result', models.TextField(blank=True, verbose_name='改善結果')),
                ('reduction_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='削減時間(Hr/月)')),
                ('effect_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='効果額(円/月)')),
                ('comment', models.TextField(blank=True, verbose_name='コメント')),
                ('contribution_business', models.CharField(blank=True, max_length=255, verbose_name='貢献事業')),
                ('mindset_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='マインドセット')),
                ('idea_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='アイデア工夫')),
                ('hint_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='みんなのヒント')),
                ('before_image_path', models.CharField(blank=True, max_length=255, verbose_name='改善前画像')),
                ('after_image_path', models.CharField(blank=True, max_length=255, verbose_name='改善後画像')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_improvement_proposals', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='improvement_proposals', to='proposals.department')),
                ('proposer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='improvement_proposals', to='proposals.employee')),
            ],
            options={
                'ordering': ['-submitted_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('supervisor', '監督者'), ('chief', '係長'), ('manager', '部門長'), ('committee', '改善委員')], max_length=20)),
                ('status', models.CharField(choices=[('pending', '未確認'), ('approved', '承認'), ('rejected', '差戻し'), ('hold', '保留')], default='pending', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('confirmed_name', models.CharField(blank=True, max_length=128)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('mindset_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('idea_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hint_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_actions', to='proposals.employee')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='proposals.improvementproposal')),
            ],
            options={
                'ordering': ['proposal_id', 'stage'],
                'unique_together': {('proposal', 'stage')},
            },
        ),
    ]
