# Generated by Django 5.2.8 on 2025-11-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_employee_improvementproposal_proposalapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='division',
            field=models.CharField(blank=True, max_length=100, verbose_name='事業部/課'),
        ),
        migrations.AddField(
            model_name='employee',
            name='group',
            field=models.CharField(blank=True, max_length=100, verbose_name='係'),
        ),
        migrations.AddField(
            model_name='employee',
            name='team',
            field=models.CharField(blank=True, max_length=100, verbose_name='班'),
        ),
    ]
