# Generated by Django 5.2.8 on 2025-11-20 01:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_employee_division_employee_group_employee_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='improvementproposal',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='提出日時'),
        ),
    ]
