# Generated by Django 5.2.8 on 2025-11-20 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_alter_improvementproposal_submitted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='improvementproposal',
            name='affiliation',
        ),
        migrations.AddField(
            model_name='improvementproposal',
            name='group',
            field=models.ForeignKey(blank=True, limit_choices_to={'level': 'group'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='improvement_group_proposals', to='proposals.department'),
        ),
        migrations.AddField(
            model_name='improvementproposal',
            name='section',
            field=models.ForeignKey(blank=True, limit_choices_to={'level': 'section'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='improvement_section_proposals', to='proposals.department'),
        ),
        migrations.AddField(
            model_name='improvementproposal',
            name='team',
            field=models.ForeignKey(blank=True, limit_choices_to={'level': 'team'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='improvement_team_proposals', to='proposals.department'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='group',
            field=models.ForeignKey(blank=True, limit_choices_to={'level': 'group'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_proposals', to='proposals.department'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='section',
            field=models.ForeignKey(blank=True, limit_choices_to={'level': 'section'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='section_proposals', to='proposals.department'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='team',
            field=models.ForeignKey(blank=True, limit_choices_to={'level': 'team'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='team_proposals', to='proposals.department'),
        ),
        migrations.AlterField(
            model_name='improvementproposal',
            name='department',
            field=models.ForeignKey(limit_choices_to={'level': 'division'}, on_delete=django.db.models.deletion.PROTECT, related_name='improvement_proposals', to='proposals.department'),
        ),
    ]
