# Generated by Django 5.2.8 on 2025-11-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_remove_improvementproposal_affiliation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['display_id', 'name']},
        ),
        migrations.AddField(
            model_name='department',
            name='display_id',
            field=models.IntegerField(default=0, help_text='小さい値ほど上に表示されます', verbose_name='表示順'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('staff', '従業員'), ('supervisor', '班長'), ('chief', '係長'), ('manager', '部門長'), ('committee', '改善委員')], default='staff', max_length=20),
        ),
    ]
