# Generated by Django 5.2.8 on 2025-11-22 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0008_change_userpermission_to_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('staff', '一般社員'), ('supervisor', '班長'), ('chief', '係長'), ('manager', '部門長・課長'), ('committee', '改善委員'), ('committee_chair', '改善委員長')], default='staff', help_text='ユーザーの役職', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsible_department', models.ForeignKey(blank=True, help_text='担当する部署（班長は班、係長は係、部門長・課長・改善委員は部・課）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_users', to='proposals.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ユーザープロファイル',
                'verbose_name_plural': 'ユーザープロファイル',
            },
        ),
    ]
