# Generated by Django 5.2.8 on 2025-11-22 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0009_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('before', '改善前'), ('after', '改善後')], max_length=10)),
                ('image_path', models.CharField(max_length=255, verbose_name='画像パス')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='proposals.improvementproposal')),
            ],
            options={
                'ordering': ['proposal_id', 'kind', 'display_order', 'id'],
            },
        ),
    ]
