# Generated by Django 5.2.8 on 2025-11-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0010_proposalimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('staff', '従業員'), ('supervisor', '班長'), ('chief', '係長'), ('manager', '部門長'), ('committee', '改善委員'), ('admin', 'システム管理者')], default='staff', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('staff', '一般社員'), ('supervisor', '班長'), ('chief', '係長'), ('manager', '部門長・課長'), ('committee', '改善委員'), ('committee_chair', '改善委員長'), ('admin', 'システム管理者')], default='staff', help_text='ユーザーの役職', max_length=20),
        ),
    ]
