# Generated by Django 5.2.8 on 2025-11-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0011_add_admin_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='smtp_host',
            field=models.CharField(blank=True, default='', help_text='SMTPサーバーのホスト名（例: smtp.gmail.com）', max_length=255, verbose_name='SMTPホスト'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='smtp_password',
            field=models.CharField(blank=True, default='', help_text='SMTP認証に使用するパスワード', max_length=255, verbose_name='SMTP認証パスワード'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='smtp_port',
            field=models.IntegerField(blank=True, help_text='SMTPポート番号（例: 587）', null=True, verbose_name='SMTPポート'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='smtp_user',
            field=models.CharField(blank=True, default='', help_text='SMTP認証に使用するユーザー名またはメールアドレス', max_length=255, verbose_name='SMTP認証ユーザー'),
        ),
    ]
