# Generated by Django 5.2.8 on 2025-11-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0012_add_smtp_fields_to_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='ユーザーのメールアドレス', max_length=254, verbose_name='メールアドレス'),
        ),
    ]
