# Generated by Django 5.2.8 on 2025-11-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0017_improvementproposal_committee_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='improvementproposal',
            name='proposal_classification',
            field=models.CharField(blank=True, choices=[('保留提案', '保留提案'), ('努力提案', '努力提案'), ('アイディア提案', 'アイディア提案'), ('優秀提案', '優秀提案')], max_length=20, verbose_name='提案判定'),
        ),
    ]
