# Generated by Django 5.2.8 on 2025-11-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0018_alter_improvementproposal_proposal_classification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='improvementproposal',
            name='comment',
        ),
        migrations.AddField(
            model_name='improvementproposal',
            name='effect_details',
            field=models.TextField(blank=True, help_text='時間単価１７００円で計算すること。削減時間は「誰が」「どれだけ」がわかるように記入してください。', verbose_name='効果内容・効果算出'),
        ),
    ]
