# Generated by Django 5.2.8 on 2025-11-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0019_remove_improvementproposal_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='improvementproposal',
            name='serial_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='通し番号'),
        ),
    ]
