# Generated by Django 5.2.8 on 2025-11-25 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0021_improvementproposal_classification_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='improvementproposal',
            name='classification_points',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ポイント'),
        ),
        migrations.AlterField(
            model_name='improvementproposal',
            name='effect_details',
            field=models.TextField(help_text='時間単価１７００円で計算すること。削減時間は「誰が」「どれだけ」がわかるように記入してください。', verbose_name='効果内容・効果算出'),
        ),
        migrations.CreateModel(
            name='ProposalContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(blank=True, max_length=32)),
                ('employee_name', models.CharField(blank=True, max_length=128)),
                ('is_primary', models.BooleanField(default=False)),
                ('share_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='proposals.employee')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='proposals.improvementproposal')),
            ],
            options={
                'ordering': ['proposal_id', '-is_primary', 'id'],
                'unique_together': {('proposal', 'employee')},
            },
        ),
    ]
