# Generated by Django 5.2.8 on 2025-11-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0022_alter_improvementproposal_classification_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='improvementproposal',
            name='proposer_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='提案者メール'),
        ),
    ]
