# Generated by Django 5.2.8 on 2025-11-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0023_improvementproposal_proposer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalcontributor',
            name='classification_points_share',
            field=models.DecimalField(decimal_places=2, default=0, help_text='提案ポイントを共同提案者で均等割りした値', max_digits=8, verbose_name='提案ポイント按分'),
        ),
    ]
