# Generated by Django 5.2.8 on 2025-11-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0024_proposalcontributor_classification_points_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('regular', '社員'), ('intern', '実習生'), ('temporary', '人材派遣'), ('skilled', '特定技能'), ('contract', '嘱託'), ('part_time', 'パート')], default='regular', max_length=20, verbose_name='雇用形態'),
        ),
    ]
