# Generated by Django 5.2.8 on 2025-11-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0025_employee_employment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalapproval',
            name='safety_flag',
            field=models.BooleanField(default=False, verbose_name='安全'),
        ),
        migrations.AddField(
            model_name='proposalapproval',
            name='sdgs_flag',
            field=models.BooleanField(default=False, verbose_name='SDGs'),
        ),
    ]
