# Generated by Django 5.2.8 on 2025-11-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0026_proposalapproval_safety_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalcontributor',
            name='reward_amount',
            field=models.DecimalField(decimal_places=0, default=0, help_text='報奨金（提案ポイント×300）を共同提案者で均等割りした値', max_digits=10, verbose_name='報奨金按分'),
        ),
    ]
